export const DEFAULT_ANIMATION_DURATION_MS = 500;
export const EASING_SETTINGS = [0.8, 0, 0.96, 0.8];
export const DEFAULT_EASING_FUNCTION = `ease`;
export const DEFAULT_TIMING_FUNCTION = `cubic-bezier(0.25, 0.8, 0.25, 1)`;
export const DEFAULT_TIMING = `${DEFAULT_ANIMATION_DURATION_MS}ms ${DEFAULT_TIMING_FUNCTION}`;
export const ANIMATION_DURATION_SHORT = 150;
export const ANIMATION_DURATION_MEDIUM = 600;
