export const DEFAULT_ANIMATION_DURATION_MS = 500;
export const DEFAULT_TIMING_FUNCTION = `cubic-bezier(0.25, 0.8, 0.25, 1)`;
export const DEFAULT_TIMING = `${DEFAULT_ANIMATION_DURATION_MS}ms ${DEFAULT_TIMING_FUNCTION}`;
